#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d o o o o o

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autostart apps
sxhkd &
picom --config $HOME/.config/picom.conf &
nitrogen --restore & 
dunst &
$HOME/.config/polybar/launch.sh &
